### PR TITLE
I hope i don't have to do any more code.. Pls pranav pls!!

### PR DESCRIPTION
**Pull request by SShastri19**
This is my application to avoid coding. Hope it will be taken into consideration. Yours sincerely. Thank you

### CODE REVIEW

**Comment by ballaneypranav** [comment]
Duly noted. You won't have to write another line of code xD

However, when I manage to generalize this build so that any team can use it, can we make a few preset themes? 

So that they get some basic designs right away without writing much code, with accessibility and responsiveness built in.

**Comment by SShastri19** [comment]
That's sounds like it'll be really helpful for everyone. We can do that...

P.s. I was just kidding about not writing code. I'm not quite good at it
but if you need any help with that let me know.

**Comment by ballaneypranav** [comment]
I would love it if you could help with the CSS for themes! We can get started with this after 15th, since I'm planning to make a preliminary release of our iGEM upload tool to all the teams and a lot of work is left there. Till then, can you start learning HTML, CSS and Bootstrap if you don't know already?

I bought a course on Udemy last year which was quite good. I can give you my password - it should take you about 12 hours if starting from scratch, but if you know a little bit, only 5-6 hours should be enough.

**Comment by SShastri19** [comment]
Sure... I'd love to work on it. It's set then...
What's the name of the course?

**Pull request merged**
